SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  OPTIMIZER: "ADAM"
  AMSGRAD: True
  WEIGHT_DECAY: 0.00001
  LR_SCHEDULER: "ReduceLROnPlateau"
  LR_PATIENCE: 2
  LR_FACTOR: 0.5
  LR_MIN: 1e-6
  PATIENCE: 3
  PATIENCE_MIN_DELTA: 0.001
  WARMUP_ITERS: 1000

DATALOADER:
  NUM_WORKERS: 8

DATASETS:
  DATA_DIR: 'data/nl'
  SELECT_VISIBLE: True
  SELECT_INVISIBLE: True
  BUFFER: .4
  BINARY_TRESHOLD: .5
  SELECT_URBAN: True
  SELECT_RURAL: True
  PATCHES_DIR: 'patches_25'
  DOWNSAMPLE_FACTOR: .32
  TRAIN_SAMPLE: False
  TRAIN_SAMPLE_RATE: 1.
  TEST_SAMPLE: False
  TEST_SAMPLE_RATE: 1.
  RESOLUTIONS: [512, 256, 128, 64, 32]
  IMG_SIZE: 512
  SPLIT: False
  CREATE_PATCHES: False
  REFERENCE_TYPE: 'test'

MODEL:
  RUN_TYPE: "predict"
  PACKAGE: "models.cadnet.cadnet"
  CLASS_NAME: "CadNET"
  BACKBONE: "coanet"
  DEVICE: "cuda:1"
  USE_PRETRAINED: False
  TRAINED_MODEL: 'model_00005.pth'
  USE_MULTI: False
  USE_COA: True
  USE_BRK: True
  
  WRITE_MOSAIC_RASTER: True
  WRITE_RASTER_STATS: True
  WRITE_MOSAIC_VECTOR: True
  WRITE_VECTOR_STATS: True

  TEST_OVERLAP_50: True
  WRITE_PATCH_PREDS_SAMPLE_RATE: 50
  MOSAIC_TILE: ['120000-430000']
  MOSAIC_CLUSTER: 138
  TYPE_POLY_PRED: 'poly'
  MAX_DIST: 5.

POLY:
  TOLERANCE: 10.